### PR TITLE
Changes for compilation using AppleClang on MacOS

### PR DESCRIPTION
**Pull request by wbenoot**
Eventhough Boost was found, it had some issues with finding unit_test_framework.
Implicit casting caused troubles only when using Clang compiler, GCC worked fine.

### CODE REVIEW

**Comment by igorauad** [comment]
Hi @wbenoot ,

Thanks for the PR. These changes are a little tedious to review manually, so I thought I should make a script to reproduce them. I've pushed the changes in c079787, which were generated by the following script:

```bash
#!/bin/bash
cmd='sed -i '' \
    -e "s/(SQRT2_2 + SQRT2_2i)/{SQRT2_2, SQRT2_2}/g" \
    -e "s/(-SQRT2_2 - SQRT2_2i)/{-SQRT2_2, -SQRT2_2}/g" \
    -e "s/(-SQRT2_2 + SQRT2_2i)/{-SQRT2_2, SQRT2_2}/g" \
    -e "s/(SQRT2_2 - SQRT2_2i)/{SQRT2_2, -SQRT2_2}/g" \
    -e "s/(+SQRT2_2 + SQRT2_2i)/{SQRT2_2, SQRT2_2}/g" \
    -e "s/(-SQRT2_2 + SQRT2_2i)/{-SQRT2_2, SQRT2_2}/g" \
    -e "s/(+SQRT2_2 - SQRT2_2i)/{SQRT2_2, -SQRT2_2}/g" \
    -e "s/(-SQRT2_2 - SQRT2_2i)/{-SQRT2_2, -SQRT2_2}/g" \
    -e "s/(-1.0j)/{ 0, -1.0 }/g" \
    -e "s/(+1.0j)/{ 0, 1.0 }/g" \
    -e "s/1j/{ 0, 1.0 }/g" \
    $1 && clang-format -i $1'
find . -name *.h -path "./lib/*" -exec bash -c "$cmd" -- {} \;
find . -name *.cc -path "./lib/*" -exec bash -c "$cmd" -- {} \;
find . -name *.hh -path "./lib/*" -exec bash -c "$cmd" -- {} \;
find . -name *.cc -path "./bench/*" -exec bash -c "$cmd" -- {} \;
```

Could you please rebase your PR so that I can check if there was any change left? 

I also see the change about finding boost. I wonder if we should use `include(GrBoost)` like this: https://github.com/gnuradio/gnuradio/blob/76831245122fdbd2ce52951d8749ef3b4ff8e496/gr-fft/CMakeLists.txt#L11. Could you test and see if that solves the problem like `find_package(Boost REQUIRED unit_test_framework)` did?

**Comment by igorauad** [comment]
Also, I've been meaning to test the compilation using Clang on CI for some time. The changes are in 2c3fdec. However, I never figured out a solution for the issue reported in https://github.com/igorauad/gr-dvbs2rx/pull/4#issuecomment-1002704446.

Have you tried running `ctest` after your Clang compilation? Do they work?

**Comment by wbenoot** [comment]
hi @igorauad 

I rebased, there was only one file not updated by your script. 
Will check for the Boost inclusion soon, and I'll try to have a look at the Clang build.

**Comment by igorauad** [comment]
Thanks!

**Comment by igorauad** [comment]
@wbenoot I will close this PR. The fixes were already incorporated into the master branch, including your commit 6d3ed1caca0c3759d2b1b63b8ab62f73765fa1c6.

**Pull request closed without merging**
